items = [
    {"id": 1, "product": "Dashcams", "model": "Qcy F24", "price": 4800, "amount": 5},
    {"id": 2, "product": "Dashcams", "model": "70mai A400", "price": 3500, "amount": 6},
    {"id": 3, "product": "Dashcams", "model": "70mai A400s", "price": 4800, "amount": 7},
    {"id": 4, "product": "Dashcams", "model": "70mai A500s", "price": 6600, "amount": 8},
    {"id": 5, "product": "Dashcams", "model": "70mai A800s", "price": 7800, "amount": 9},
    {"id": 6, "product": "LED Lights", "model": "Keon Sondra", "price": 8300, "amount": 10},
    {"id": 7, "product": "LED Lights", "model": "Lux Led", "price": 3900, "amount": 5},
    {"id": 8, "product": "LED Lights", "model": "SB Led", "price": 300, "amount": 6},
    {"id": 9, "product": "X-Films", "model": "X-Films", "price": 280, "amount": 7},
    {"id": 10, "product": "Car Cover", "model": "Water proof", "price": 2500, "amount": 8},
    {"id": 11, "product": "Car Cover", "model": "Dust proof", "price": 1500, "amount": 9},
    {"id": 12, "product": "Car Mattings", "model": "2 rows deep dish", "price": 3000, "amount": 10},
    {"id": 13, "product": "Car Mattings", "model": "3 rows deep dish", "price": 3800, "amount": 5},
    {"id": 14, "product": "Pristine Car Care", "model": "Nano wax 500ml", "price": 750, "amount": 6},
    {"id": 15, "product": "Pristine Car Care", "model": "All purpose cleaner", "price": 400, "amount": 7},
    {"id": 16, "product": "Pristine Car Care", "model": "Car shampoo w/ max 1 liter", "price": 200, "amount": 8},
    {"id": 17, "product": "Pristine Car Care", "model": "Luxor pink car shampoo w/max 1 liter", "price": 250, "amount": 9},
    {"id": 18, "product": "Pristine Car Care", "model": "Windshield washer", "price": 150, "amount": 10},
    {"id": 19, "product": "Other Accessories", "model": "Garnish set", "price": 2500, "amount": 5},
    {"id": 20, "product": "Other Accessories", "model": "Skid plate", "price": 2500, "amount": 6},
    {"id": 21, "product": "Other Accessories", "model": "Tow hitch receiver", "price": 6500, "amount": 7},
    {"id": 22, "product": "Other Accessories", "model": "Car alarm", "price": 2500, "amount": 8},
    {"id": 23, "product": "Other Accessories", "model": "Push start alarm system", "price": 8000, "amount": 9},
    {"id": 24, "product": "Other Accessories", "model": "Android headunit w/ OEM panel", "price": 12000, "amount": 10},
    {"id": 25, "product": "Other Accessories", "model": "Tesla style headunit", "price": 50000, "amount": 5},
]
